config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :tools, only: [:create, :new, :index, :show, :destroy, :edit, :update] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:show, :index, :update] do
    resources :notifications, only: [:update]
  end
end

app/models/tool.rb
class Tool < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, :brand, :price, :category, :description, :address, presence: true
  validates :price, numericality: true
  mount_uploader :photo, PhotoUploader
  validates :photo, presence:true

  def dates_to_array
    # split into array of 2
    dates_array = self.date.to_s.gsub(/\"/, "").split("],")
    # split elements of array into arrays of 2
    dates_array.map! do |date|
      date.gsub(/\[|\]/,"").gsub(/\"/, "").gsub(" ", "").split(",")
    end
    # convert to dates format
    dates_array.map do |two_dates|
      two_dates.map do |date|
        Date.parse(date)
      end
    end
  end

  def all_booked_dates
    all_bookings = self.bookings
    p all_bookings
    booked_dates = []
    all_bookings.each do |booking|
      dates = booking.dates_to_array
      if dates.length == 2
        i = dates[0]
        while i <= dates[1]
          booked_dates.push(i)
          i+=1
        end
      elsif dates.length == 1
        booked_dates.push(dates)
      end
    end
    booked_dates
  end

  def original_available_dates
    available_ranges = self.dates_to_array
    available_dates = []
    available_ranges.each do |dates|
      if dates.length == 2
        i = dates[0]
        while i <= dates [1]
          available_dates.push(i)
          i+=1
        end
      elsif dates.length == 1
        available_dates.push(dates)
      end
    end
    available_dates
  end

  def available_dates_after_bookings
    p booked = self.all_booked_dates
    p available = self.original_available_dates
    final_available = available.select { |date| booked.include?(date)!= true }
    p final_available
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :set_tool, except: [:index, :new, :create]
  skip_before_action :authenticate_user!, only: :index
  skip_before_action :authenticate_user!, only: :show

  def index
    search = params[:search]
    search_command = []
    search_values = {}
    if !search.nil?
      search.each do |filter|
        if filter[1] != ""
          value = ""
          if filter[0] == "category" || filter[0] == "brand"
            value = filter[1]
            search_command << "#{filter[0]} = :#{filter[0]}"
          elsif filter[0] == "price"
            value = filter[1].to_i
            search_command << "#{filter[0]} <= :#{filter[0]}"
          elsif filter[0] == "location"
          elsif filter[0] == "date"
          end
          search_values[filter[0].to_sym] = value
        end
      end
    end
    @tools = policy_scope(Tool).where(search_command.join(" AND "), search_values)
    if search[:location] != ''
      @tools = filter_by_location(@tools, search[:location])
    end
    if search[:date] != ''
      @tools = filter_by_date(@tools, search['date'])
    end
    @markers = @tools.map do |tool|
      {
        lat: tool.latitude,
        lng: tool.longitude,
        info_window: render_to_string(partial: "info_window", locals: { tool: tool })
      }
    end
  end

  def show
    @map_tools = Tool.geocoded

    @markers = @map_tools.map do |tool|
      {
        lat: @tool.latitude,
        lng: @tool.longitude
      }
    end
  end

  def new
    @tool = Tool.new
    authorize @tool
  end

  def create
    @tool = Tool.new(tool_params)
    date_array = params[:tool][:date].split(' to ')
    authorize @tool
    @tool.user = current_user
    @tool.date = date_array
    if @tool.save
      redirect_to tool_path(@tool)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @tool.update(tool_params)
    redirect_to tool_path(@tool)
  end

  def destroy
    @tool.destroy
    redirect_to bookings_path
  end

  private

  def tool_params
    params.require(:tool).permit(:name, :brand, :price, :category, :description, :photo, :address)
  end

  def set_tool
    @tool = Tool.find(params[:id])
    authorize @tool
  end

  def filter_by_date(tools_array, searched_dates)
    selection = list_dates(searched_dates)
    @tools = tools_array.select do |tool|
      selection.all? { |e| tool.available_dates_after_bookings.include?(e) }
    end
    p @tools
  end

  def list_dates(dates_string)
    dates = dates_string.split(' to ')
    dates.map! { |date| Date.parse(date)}
    list = []
    i = dates[0]
    if dates.length == 2
      while i <= dates[1] do
        list.push(i)
        i += 1
      end
    else
      list.push(dates[0])
    end
    list
  end

  def filter_by_location(array, address)
    all_tools = Tool.near(address, 10)
    @tools = array.select { |tool| all_tools.include?(tool) }
  end

end

app/views/tools/_info_window.html.erb
<!-- <h6><%#= tool.name %></h6> -->
<!-- <a class="btn small-button" href="<% tool_path(tool) %>">View</a> -->

<%= render 'shared/tool_card', tool: tool%>

app/views/tools/edit.html.erb
<div class="full-page">
  <div class= "page-picture" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path 'zbegzvemk951d8zgkmba', crop: :fill %>)">
      <div class="center-form-add-tools ">
        <%= simple_form_for(@tool) do |f| %>
            <%= f.input :name%>
            <%=f.input :category, input_html: {class: "select2"}, required: false, collection: ['Trowel', 'Square Shovel', 'Pointed Shovel', 'Garden Fork', 'Potato Fork', 'Spading Fork', 'Border Forks', 'Broadfork', 'Compost Fork', 'Pick', 'Hoe', 'Auger', 'Trench Shovel', 'Post Hole Pincer', 'Wheel Edger', 'Step-On Edger', 'Edging Shears', 'Electric Edger', 'Gas Edger', 'Lawn Mower', 'Leaf Blower', 'String Trimmer', 'Mulcher', 'Spreader', 'Sprinkler', 'Rake', 'Aerator', 'Hose', 'Bulb Planter', 'Hand Weeder', 'Hand Seeder', 'Seeder Row Planter', 'Tiller', 'Planting Dibble', 'Twist Tiller', 'Cultivator', 'Soil Scoop', 'Hand Pruner', 'Hedge Shears', 'Pruning Saw', 'Lopper', 'Pole pruner', 'Tree Pruner', 'Snips', 'Topiary Shears', 'Trailer Sprayer', 'Skid Sprayer', 'Backpack Sprayer', 'Handheld Sprayer', 'Broadcast Sprayer', 'Chainsaw', 'Composter', 'Wheelbarrow', "Lopper"]%>
            <%=f.input  :brand,input_html: {class: "select2"}, required: false, collection: ['A.M. Leonard', 'Bionic Gloves/H&B', 'Einhell', 'Bond Manufacturing', 'Centurion Brands', 'CobraHead LLC', 'Corona', 'Earthquake', 'ERA Group', 'Fence Armor', 'Florian Tools', 'Foxgloves', 'Gardener’s Supply Company', 'GreenStalk Gardening Systems', 'High Caliper Growing', 'Maine Garden Products Div. of Bartlett Bench & Wire Inc', 'Melnor', 'Radius Garden', 'Redback', 'Root Assassin LLC', 'Seeding Square', 'Gardena', 'Stihl', 'Kaercher', 'Husqvarna', 'Mantis', 'Trumper', 'Lifetime', 'Scenic road', 'Devaon']%>
            <%= f.input :description %>
            <%= f.input :price, :label => 'Price / day (€)' %>
            <%= f.input :address %>
            <%= f.input :date, as: :string, :label => 'Available dates', input_html: {class: "datepicker"}, require: false%>
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
            <%= f.button  :submit, class: "btn btn-success" %>
        <% end %>
      </div>
  </div>
</div>

app/views/tools/index.html.erb
<div class="container min-height">
    <h2 class="title-index-page">Available Tools</h2>
  <div class="index-grid-with-filter">
    <div>
        <div class="filter-box">
        <div class="line-of-buttons pa-0 ">
          <button class="btn button" id="tools-list-button">List</button>
          <button class="btn button button-unselected" id="tools-map-button">Map</button>
        </div>
        <%price = params[:search][:price] if !params[:search].nil?%>
        <%location = params[:search][:location] if !params[:search].nil?%>
        <%category = params[:search][:category] if !params[:search].nil?%>
        <%brand = params[:search][:brand] if !params[:search].nil?%>
        <%date = params[:search][:date] if !params[:search].nil?%>

        <div class="filter">
          <%= simple_form_for :search, url: tools_path, method: "GET", html: { class: '' } do |f| %>
            <%=f.input :category, input_html: {class: "select2"}, selected: category, required: false, collection: ['', 'Trowel', 'Square Shovel', 'Pointed Shovel', 'Garden Fork', 'Potato Fork', 'Spading Fork', 'Border Forks', 'Broadfork', 'Compost Fork', 'Pick', 'Hoe', 'Auger', 'Trench Shovel', 'Post Hole Pincer', 'Wheel Edger', 'Step-On Edger', 'Edging Shears', 'Electric Edger', 'Gas Edger', 'Lawn Mower', 'Leaf Blower', 'String Trimmer', 'Mulcher', 'Spreader', 'Sprinkler', 'Rake', 'Aerator', 'Hose', 'Bulb Planter', 'Hand Weeder', 'Hand Seeder', 'Seeder Row Planter', 'Tiller', 'Planting Dibble', 'Twist Tiller', 'Cultivator', 'Soil Scoop', 'Hand Pruner', 'Hedge Shears', 'Pruning Saw', 'Lopper', 'Pole pruner', 'Tree Pruner', 'Snips', 'Topiary Shears', 'Trailer Sprayer', 'Skid Sprayer', 'Backpack Sprayer', 'Handheld Sprayer', 'Broadcast Sprayer', 'Chainsaw', 'Composter', 'Wheelbarrow', "Lopper"]%>
            <%=f.input :brand,input_html: {class: "select2"}, selected: brand, required: false, collection: ['', 'A.M. Leonard', 'Bionic Gloves/H&B', 'Einhell', 'Bond Manufacturing', 'Centurion Brands', 'CobraHead LLC', 'Corona', 'Earthquake', 'ERA Group', 'Fence Armor', 'Florian Tools', 'Foxgloves', 'Gardener’s Supply Company', 'GreenStalk Gardening Systems', 'High Caliper Growing', 'Maine Garden Products Div. of Bartlett Bench & Wire Inc', 'Melnor', 'Radius Garden', 'Redback', 'Root Assassin LLC', 'Seeding Square', 'Gardena', 'Stihl', 'Kaercher', 'Husqvarna', 'Mantis', 'Trumper', 'Lifetime', 'Scenic road', 'Devaon']%>
            <%=f.input :price, as: :float, required: false, input_html: { min: "0" }, input_html: {value: price}, :label => 'Maximum price / day (€)'%>
            <%=f.input :location, required: false, input_html: {value: location, id: 'tool_address' }%>
            <%= f.input :date, input_html: {class: "datepicker", value: date }, required: false%>
            <%=f.submit "Search", class: "btn button" %>
          <% end %>
        </div>
      </div>
    </div>

    <div>
      <div id="map-container"  class="hidden">
        <%= render 'shared/map' %>
      </div>
      <div id="tools-list-show" class="">
        <div class="cards-grid">
          <% @tools.each do |tool| %>
            <%= render 'shared/tool_card', tool: tool%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tools/new.html.erb
<div class="full-page">
  <div class= "page-picture" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path 'zbegzvemk951d8zgkmba', crop: :fill %>)">
      <div class="center-form-add-tools ">
        <%= simple_form_for(@tool) do |f| %>
            <%= f.input :name%>
            <%=f.input :category, input_html: {class: "select2"}, required: false, collection: ['Trowel', 'Square Shovel', 'Pointed Shovel', 'Garden Fork', 'Potato Fork', 'Spading Fork', 'Border Forks', 'Broadfork', 'Compost Fork', 'Pick', 'Hoe', 'Auger', 'Trench Shovel', 'Post Hole Pincer', 'Wheel Edger', 'Step-On Edger', 'Edging Shears', 'Electric Edger', 'Gas Edger', 'Lawn Mower', 'Leaf Blower', 'String Trimmer', 'Mulcher', 'Spreader', 'Sprinkler', 'Rake', 'Aerator', 'Hose', 'Bulb Planter', 'Hand Weeder', 'Hand Seeder', 'Seeder Row Planter', 'Tiller', 'Planting Dibble', 'Twist Tiller', 'Cultivator', 'Soil Scoop', 'Hand Pruner', 'Hedge Shears', 'Pruning Saw', 'Lopper', 'Pole pruner', 'Tree Pruner', 'Snips', 'Topiary Shears', 'Trailer Sprayer', 'Skid Sprayer', 'Backpack Sprayer', 'Handheld Sprayer', 'Broadcast Sprayer', 'Chainsaw', 'Composter', 'Wheelbarrow', "Lopper"]%>
            <%=f.input  :brand,input_html: {class: "select2"}, required: false, collection: ['A.M. Leonard', 'Bionic Gloves/H&B', 'Einhell', 'Bond Manufacturing', 'Centurion Brands', 'CobraHead LLC', 'Corona', 'Earthquake', 'ERA Group', 'Fence Armor', 'Florian Tools', 'Foxgloves', 'Gardener’s Supply Company', 'GreenStalk Gardening Systems', 'High Caliper Growing', 'Maine Garden Products Div. of Bartlett Bench & Wire Inc', 'Melnor', 'Radius Garden', 'Redback', 'Root Assassin LLC', 'Seeding Square', 'Gardena', 'Stihl', 'Kaercher', 'Husqvarna', 'Mantis', 'Trumper', 'Lifetime', 'Scenic road', 'Devaon']%>
            <%= f.input :description %>
            <%= f.input :price, :label => 'Price / day (€)' %>
            <%= f.input :address %>
            <%= f.input :date, as: :string, :label => 'Available dates', input_html: {class: "datepicker"}%>
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
            <%= f.button  :submit, class: "btn btn-success" %>
        <% end %>
      </div>
  </div>
</div>

app/views/tools/show.html.erb
<div>
  <div class="container min-height" id="margin-main">
    <div class="row">
      <div class="left col-8">
        <h2 class="mb-4" ><%= @tool.name %></h2>
        <p> <strong>Brand: </strong>  <%= @tool.brand %></p>
        <p><strong> Category: </strong><%= @tool.category %></p>
        <p><strong>Address: </strong><%= @tool.address %></p>
        <div class="description">
          <p class="mb-1"><strong>Description: </strong></p>
          <p><%= @tool.description %></p>
        </div>
        <p><strong>Owner: </strong><%= @tool.user.first_name %> <%= @tool.user.last_name %></p>
        <div class="price">
          <p><strong>Price / day: </strong><%='%.2f' % @tool.price.to_f%> €</p>

          <div class="booking-card">
            <% if @tool.user != current_user%>
              <%= link_to "Add booking", new_tool_booking_path(@tool), class: "btn button" %>
            <%end%>

            <% if policy(@tool).destroy?%>
              <%= link_to "Edit tool", edit_tool_path(@tool), class: "edit_btn btn button" %>
            <% end %>

            <% if policy(@tool).destroy?%>
              <%= link_to 'Delete tool', tool_path(@tool), method: :delete, class: "btn button" %>
            <% end %>
          </div>
        </div>
      </div>


      <div class="col-4">
        <%= cl_image_tag @tool.photo, class: "tool_image" %>
        <div
          id="map"
          class="map-styling"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        ></div>
    </div>
  </div>
</div>