config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :tools, only: [:create, :new, :index, :show, :destroy, :edit, :update] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:show, :index, :update] do
    resources :notifications, only: [:update]
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :tool
  # has_one :user, through: :tool
  has_many :notifications, dependent: :destroy
  validates :dates, presence: true

  def self.own_bookings(user)
    self.where(user: user)
  end

  def self.own_tool_bookings(user)
    user_tools = Tool.where(user: user)
    bookings = []
    user_tools.each do |tool|
      booking_list = self.where(tool: tool)
      if !booking_list.blank?
        booking_list.each { |individual_booking| bookings << individual_booking}
      end
    end
    bookings
  end

  def dates_to_array
    dates_array = self.dates.to_s.gsub(/\[|\]/,"").gsub(/\"/, "").split(",")
    dates_array.map! { |date| Date.parse(date) }
  end
end

app/controllers/bookings_controller.rb
 class BookingsController < ApplicationController
  before_action :set_booking, only: [:update]

  def index
    @bookings = policy_scope(Booking)
    @own_bookings = Booking.own_bookings(current_user)
    @user_tool = Booking.own_tool_bookings(current_user)
    @tools = Tool.where(user: current_user)
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
    @tool = @booking.tool
  end

  def create
    @tool = Tool.find(params[:tool_id])
    @booking = Booking.new(bookings_params)
    if params[:booking][:dates] != ""
      @booking.dates = params[:booking][:dates].split(' to ')
      if @booking.dates_to_array.length == 1
        @booking.dates = "[#{@booking.dates_to_array[0].to_s}, #{@booking.dates_to_array[0].to_s}]"
      end
    end
    @booking.user = current_user
    @booking.tool = @tool
    if @booking.save
      # redirect_to tool_path(@tool)
      redirect_to booking_path(@booking)
    else
      render :new
    end
    authorize @booking
    notification_request(@booking)
  end

  def new
    @tool = Tool.find(params[:tool_id])
    @booking = Booking.new
    authorize @booking
  end

  def update
    booking_data = bookings_params
    response = booking_data["confirmation"]
    if response == "true"
      @booking.confirmation = true
    else
      @booking.confirmation = false
    end
    @booking.save
    notification_response(@booking, response)
    redirect_to @booking
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def bookings_params
    params.require(:booking).permit(:comment, :pickup_time, :confirmation)
  end

  def notification_response(booking, response)
    p response
    if response == "true"
      text = "Your booking of the #{@booking.tool.name.downcase} has been confirmed."
    else
      text = "Your booking of the #{@booking.tool.name.downcase} has been declined."
    end
    notification = Notification.new(message: text, read: false)
    notification.user = booking.user
    notification.booking = booking
    notification.save
  end

  def notification_request(booking)
    notification = Notification.new(message: "You have received a new booking request for your tool '#{@booking.tool.name.downcase}'", read: false)
    notification.user = booking.tool.user
    notification.booking = booking
    notification.save
  end
end

app/views/bookings/index.html.erb
<div class="container mbot-40 min-height">
  <div class="profile-layout">
    <div>
      <div class="align-content-center">
        <% if current_user.photo? %>
           <%= cl_image_tag current_user.photo, class: "avatar-vlarge" %>
         <% else %>
           <%= cl_image_tag 'snmjibatw66rduqpmt3b', class: "avatar-vlarge" %>
         <% end %>
        <h2 class="main-title-spacing mtop-20">Hi, <%=current_user.first_name%> <%=current_user.last_name%></h2>
      </div>
      <div class="align-edit-btn">
        <%= link_to 'Edit Profile', edit_user_registration_path, class: "btn button edit-btn" %>
      </div>
      <div class="line-of-buttons pa-15">
        <button class="btn button" id="profile-bookings-button">My Bookings</button>
        <button class="btn button button-unselected" id="profile-tools-button">My Tools</button>
      </div>
      <div class="notifications">
        <% if current_user.notifications.where(read: false).empty? %>
          <p class='my-0 not-header'> <span class='px-2'> <i class="fas fa-envelope"></i> </span> You have 0 notifications </p>
        <% else %>
          <p class='not-header'> <span class='px-2'> <i class="fas fa-envelope"></i> </span> Your notifications </p>
          <% current_user.notifications.where(read: false).each do |notification| %>
            <p class="notification"> <%= link_to notification.message, booking_notification_path(notification.booking, notification), method: :patch %> </p>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="ml-4" id="profile-bookings-show">
      <h3 class="main-title-spacing">Tools I Booked</h3>
      <% @own_bookings.each do |booking| %>
        <%= render 'shared/booking_card', booking: booking%>
      <% end %>

      <h3 class="mtop-20 main-title-spacing" >Bookings For My Tools</h3>
      <% @user_tool.each do |booking| %>
        <%= render 'shared/booking_card', booking: booking%>
      <% end %>
    </div>
    <div class="ml-4 hidden" id="profile-tools-show">
      <h3 class="main-title-spacing">My Tools</h3>
      <div class="cards-grid-2">
        <% @tools.each do |tool| %>
          <%= render 'shared/tool_card', tool: tool%>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/bookings/new.html.erb
<div class="container mtop-25 d-flex justify-content-between min-height">

  <div class="booking-form">
    <h2 class="mb-4"> Make a booking </h2>
    <%= simple_form_for([@tool, @booking], html: { class: '' }) do |f| %>
      <%= f.input :dates, as: :string, input_html: {class: "datepicker booking-dates"}, require: true%>
      <%= f.input :pickup_time, hint: 'Suggest a time to pick up the tool on the start date of your booking. The owner will let you know if the time works.' %>
      <%= f.input :comment, hint: 'Leave a message for the onwer (optional)' %>
      <%= f.button :submit, class: 'button' %>
  <% end %>
  </div>
  <div class="card-tool-booking-outer">
    <div class="card-tool-booking">
      <%= cl_image_tag @tool.photo, crop: :fill, class: "tool_image" %>
      <h2 class='tool-name'><%= @tool.name %></h2>
      <p class='tool-category'><%= @tool.category %>, <%= @tool.brand %></p>
      <p class='tool-description smaller-spacing' id='price-per-day' data-price='<%=@tool.price%>'>Price/day: <%='%.2f' % @tool.price.to_f%> €</p>
      <p class='tool-description smaller-spacing' id='days'>Days: 1 </p>
      <p class='tool-price' id='total-price'>Total price: <%='%.2f' % @tool.price.to_f%> € </p>
    </div>
  </div>
</div>

<div class='hidden' id='availabilities'> <%= @tool.date %></div>

<%dates = @tool.available_dates_after_bookings %>
<% dates.each do |date| %>
  <div class='hidden real-availabilities'><%= date %></div>
<% end %>

app/views/bookings/show.html.erb
<div class="container mtop-25 d-flex justify-content-between min-height ">
  <div class="flex-grow mr-5">
    <h2 class='mb-4'>Your booking</h2>
    <div class="booking-container">
      <div class="card-info-row">
        <div class="status-line">
        <!-- <span>Status:</span> -->
          <% if @booking.confirmation == nil %>
            <p>Status: Confirmation pending</p>
          <% elsif @booking.confirmation %>
            <p><strong>Status: </strong>Booking confirmed</p>
          <% else %>
            <p><strong>Status: </strong>Booking declined</p>
          <% end %>
        </div>
        <%confirmation = @booking.confirmation%>
        <p>
          <%if confirmation.nil?%>
            <i class="booking-status far fa-circle"></i>
          <%elsif confirmation%>
            <i class="booking-status far fa-check-circle"></i>
          <%elsif !confirmation%>
            <i class="booking-status far fa-times-circle"></i>
          <%end%>
        </p>
      </div>
        <% if current_user == @tool.user %>
          <p>
            <span><strong>Hirer:</strong></span>
            <span><%= @booking.user.first_name%> <%= @booking.user.last_name%></span>
          </p>
          <p>
            <span><strong>Comment:</strong></span>
            <span><%= @booking.comment %></span>
          </p>
        <% else %>
          <p>
            <span><strong>Owner:</strong></span>
            <span><%= @tool.user.first_name %> <%= @tool.user.last_name %></span>
          </p>
        <% end %>
          <p>
            <span><strong>Booking period:</strong></span>
            <span>
              <%=@booking.dates_to_array[0]%> - <%=@booking.dates_to_array[1]%></span>
          </p>
          <p>
            <span><strong>Suggested pickup time:</strong></span>
            <span><%= @booking.pickup_time.to_s.match(/\d{2}:\d{2}/)%></span>
          </p>
      </div>
    <div class="d-flex mb-3">
      <%if current_user == @tool.user && @booking.confirmation.nil?%>
        <%= simple_form_for(@booking) do |f| %>
          <%= f.input :confirmation, :as => :hidden, :input_html => { :value => "true" }%>
          <%= f.button :submit, 'Accept Booking', class: 'button  mr-10' %>
        <% end %>
        <%= simple_form_for(@booking) do |f| %>
          <%= f.input :confirmation, :as => :hidden, :input_html => { :value => "false" }%>
          <%= f.button :submit, 'Deny Booking', class: 'button' %>
        <% end %>
      <%end%>
      <%if current_user == @tool.user && @booking.confirmation == true%>
        <%= simple_form_for(@booking) do |f| %>
          <%= f.input :confirmation, :as => :hidden, :input_html => { :value => "false" }%>
          <%= f.button :submit, 'Deny Booking', class: 'button' %>
        <% end %>
      <%end%>
    </div>
    <a class="btn button mr-10" href="/bookings">All your Bookings</a>
    <a class="btn button" href="/">Back home</a>
  </div>



  <div class="card-tool-booking-outer">
    <div class="card-tool-booking">
      <%= cl_image_tag @tool.photo, crop: :fill, class: "tool_image" %>
      <h2 class='tool-name tool-card-link'><%= link_to @tool.name, @tool%></h2>
      <p class='tool-category'><%= @tool.category %>, <%= @tool.brand %></p>
      <p class='tool-description smaller-spacing' id='price-per-day'>Price/day: <%='%.2f' % @tool.price.to_f%> €</p>
      <% days = ((@booking.dates_to_array[1]-@booking.dates_to_array[0]).to_i) + 1 %>
      <p class='tool-description smaller-spacing' id='days'>Days: <%= days %> </p>
      <p class='tool-price' id='total-price'>Total price: <%='%.2f' % (@tool.price*days).to_f%> € </p>
    </div>
  </div>

</div>