config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :tools, only: [:create, :new, :index, :show, :destroy, :edit, :update] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:show, :index, :update] do
    resources :notifications, only: [:update]
  end
end

app/views/shared/_booking_card.html.erb
<div class="card-tool mtop-10">
  <%= link_to(booking) do %>
    <div class="card-booking">
      <div class="card-tool-image-small card-tool-image-width-30pc card-tool-image-radius-left" style="background-image: url('<%= cl_image_path booking.tool.photo, height: 300, width: 400, crop: :fill %>')"></div>
      <div class="card-info-box vertical-card-align p-4 ">
        <div class="card-info-row">
          <p class="booking-tool-name"><%= booking.tool.name %></p>
          <%confirmation = booking.confirmation%>
          <p>
            <%if confirmation.nil?%>
              <i class="booking-status far fa-circle"></i>
            <%elsif confirmation%>
              <i class="booking-status far fa-check-circle"></i>
            <%elsif !confirmation%>
              <i class="booking-status far fa-times-circle"></i>
            <%end%>
          </p>
        </div>
        <div class="card-info-row">
          <div class="booking-time">
            <p class="booking-period">Booking period: <%=booking.dates_to_array[0]%> - <%=booking.dates_to_array[1]%></p>
            <p class="booking-pickup">Pickup time: <%=(booking.pickup_time).to_s.match(/\d{2}:\d{2}/)%></p>
          </div>
        </div>
        <div class="card-info-row">
          <% if current_user == booking.tool.user %>
            <p class="booking-tool-owner">Hirer: <%= booking.user.first_name %> <%= booking.user.last_name %></p>
          <% else %>
            <p class="booking-tool-owner">Owner: <%= booking.tool.user.first_name %> <%= booking.tool.user.last_name %></p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container d-flex justify-content-between">
    <p>© Copyright 2020 | Otto, Marie, Joris & Paul</p>
    <p>Imprint    |    Terms    |    Coockies    |    Privacy Policy    |    Site Map</p>
  </div>

</div>

app/views/shared/_map.html.erb
<div
 id="map"
 style="width: 100%;
 height: 600px;"
 data-markers="<%= @markers.to_json %>"
 data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="d-flex">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "farmer.svg" %>
    <% end %>
    <h1>AirTools</h1>
  </div>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add Tool", new_tool_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <% user_name = "Your profile" %>
          <%= link_to(bookings_path, class: "nav-link")  do %>
            <% if current_user.notifications.where(read: false).any?%>
              Your profile <sup><i class="fas fa-envelope nav-bar-envelope"></i></sup>
            <% else %>
              Your profile
            <% end %>
          <% end %>
        </li>

        <li class="nav-item dropdown">
         <% if current_user.photo? %>
           <%= cl_image_tag current_user.photo, class: "tool_image", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
         <% else %>
           <%= cl_image_tag 'snmjibatw66rduqpmt3b', class: "tool_image", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
         <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "#{current_user.first_name} #{current_user.last_name}", bookings_path, class: "dropdown-item" %>
            <%= link_to "Account", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_tool_card.html.erb
<div class="card-tool">
  <%= link_to(tool) do %>
    <div class="card-tool-image" style="background-image: url('<%= cl_image_path tool.photo, height: 300, width: 400, crop: :fill %>')"> <p class="category-text category-tag"> <%= tool.category %> </p> </div>
    <div class="card-info-box">
      <div class="card-info-row">
        <p class="subtitle"><%=tool.name%></p>
      </div>
      <div class="card-info-row mtop-5">
        <p> <span class = "info-text-bold"> <%='%.2f' % tool.price.to_f%>€ </span> <span class = "info-text">/ day</span></p>
        <p class="category-text"><%=tool.brand%></p>
      </div>
    </div>
  <%end%>
</div>